import { Eye, Newspaper, Pencil, Plus, Send, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog'
import { type Magazine, type MagazineStatus, type NewsCategory, type NewsInput, useAdminMagazines, useMagazineMutations, useNews } from './use-magazines'

const newsCategories:Record<NewsCategory,string>={gbp:'GBP',seo:'SEO',review:'口コミ',local:'ローカル'}
const emptyNews:NewsInput={title:'',body:'',source_url:null,source_name:null,published_at:new Date().toISOString().slice(0,16),category:'gbp'}

export function MagazineAdminPanel(){
  const{data:magazines=[],isLoading,error}=useAdminMagazines(),{data:news=[]}=useNews(),mutations=useMagazineMutations(),[previewId,setPreviewId]=useState<string|null>(null),[editing,setEditing]=useState<Magazine|null>(null),[newsOpen,setNewsOpen]=useState(false),[newsForm,setNewsForm]=useState<NewsInput>(emptyNews)
  const[editForm,setEditForm]=useState({title:'',summary:'',actions:'',status:'draft' as MagazineStatus}),preview=magazines.find(item=>item.id===previewId)??magazines[0]
  const busy=mutations.generate.isPending||mutations.update.isPending||mutations.send.isPending||mutations.createNews.isPending
  const beginEdit=(magazine:Magazine)=>{setEditing(magazine);setEditForm({title:magazine.title,summary:magazine.summary,actions:magazine.actions.join('\n'),status:magazine.status})}
  const saveMagazine=async(event:React.FormEvent)=>{event.preventDefault();if(!editing)return;await mutations.update.mutateAsync({id:editing.id,title:editForm.title.trim(),summary:editForm.summary.trim(),actions:editForm.actions.split('\n').map(item=>item.trim()).filter(Boolean).slice(0,3),status:editForm.status});setEditing(null)}
  const saveNews=async(event:React.FormEvent)=>{event.preventDefault();await mutations.createNews.mutateAsync({...newsForm,published_at:new Date(newsForm.published_at).toISOString()});setNewsOpen(false);setNewsForm(emptyNews)}
  const send=(magazine:Magazine)=>{if(window.confirm(`${magazine.title}を未配信の施設へメール配信しますか？`))mutations.send.mutate(magazine.id)}
  const mutationError=mutations.generate.error||mutations.update.error||mutations.send.error||mutations.createNews.error
  return <><header className="role-heading"><div><span>ADMIN</span><h1>MEOマガジン管理</h1><p>月次マガジンの生成・編集・公開・メール配信を管理します。</p></div><div className="magazine-admin-primary"><button disabled={busy} onClick={()=>mutations.generate.mutate()}><Sparkles size={15}/>{mutations.generate.isPending?'生成中…':'今月号を生成'}</button><button disabled={busy} onClick={()=>{setNewsForm(emptyNews);setNewsOpen(true)}}><Plus size={15}/>ニュース登録</button></div></header>{error&&<p className="data-error">マガジン一覧を取得できませんでした。</p>}{mutationError&&<p className="data-error">{mutationError.message}</p>}{mutations.generate.isSuccess&&<p className="data-success">今月号の下書きを生成しました。</p>}{mutations.send.isSuccess&&<p className="data-success">{mutations.send.data.sent}件へ配信しました。失敗 {mutations.send.data.failed}件。</p>}
    <div className="data-table"><div className="data-row magazine-admin-row head"><span>年月・タイトル</span><span>ステータス</span><span>配信施設</span><span>操作</span></div>{isLoading?<p className="loading-row">読み込み中…</p>:magazines.map(item=><div className="data-row magazine-admin-row" key={item.id}><div><strong>{item.year}年{item.month}月</strong><small>{item.title}</small></div><span className={`pill ${item.status==='published'?'green':'gold'}`}>{item.status==='published'?'公開中':'下書き'}</span><span>{item.deliveryCount??0}施設</span><div className="magazine-admin-actions"><button onClick={()=>setPreviewId(item.id)}><Eye size={14}/>プレビュー</button><button onClick={()=>beginEdit(item)}><Pencil size={14}/>編集</button><button className="primary-button" disabled={busy||item.status!=='published'} onClick={()=>send(item)}><Send size={14}/>配信</button></div></div>)}{!isLoading&&!magazines.length&&<p className="loading-row">マガジンはまだありません。</p>}</div>
    {preview&&<article className="magazine-admin-preview"><header><Newspaper size={19}/><div><span>プレビュー</span><h2>{preview.title}</h2></div></header><div>{preview.summary.split(/\n{2,}/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><h3>重点アクション</h3><ol>{preview.actions.map((action,index)=><li key={index}>{action}</li>)}</ol></article>}
    <section className="admin-news-list"><header><h2>登録ニュース</h2><span>{news.length}件</span></header>{news.slice(0,10).map(item=><article key={item.id}><span className="pill">{newsCategories[item.category]}</span><div><strong>{item.title}</strong><small>{item.source_name??'出典未設定'}・{new Date(item.published_at).toLocaleDateString('ja-JP')}</small></div></article>)}{!news.length&&<p className="loading-row">ニュースはまだ登録されていません。</p>}</section>
    <Dialog open={Boolean(editing)} onOpenChange={value=>!value&&setEditing(null)}><DialogContent><form className="magazine-dialog-form" onSubmit={event=>void saveMagazine(event)}><DialogHeader><DialogTitle>マガジンを編集</DialogTitle><DialogDescription>公開前に本文と重点アクションを確認してください。</DialogDescription></DialogHeader><label>タイトル<input required value={editForm.title} onChange={event=>setEditForm(current=>({...current,title:event.target.value}))}/></label><label>月次まとめ<textarea required rows={9} value={editForm.summary} onChange={event=>setEditForm(current=>({...current,summary:event.target.value}))}/></label><label>重点アクション（1行1件・最大3件）<textarea required rows={5} value={editForm.actions} onChange={event=>setEditForm(current=>({...current,actions:event.target.value}))}/></label><label>ステータス<select value={editForm.status} onChange={event=>setEditForm(current=>({...current,status:event.target.value as MagazineStatus}))}><option value="draft">下書き</option><option value="published">公開</option></select></label><DialogFooter><DialogClose type="button" className="secondary-button">キャンセル</DialogClose><button className="primary-button" disabled={busy}>保存する</button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={newsOpen} onOpenChange={setNewsOpen}><DialogContent><form className="magazine-dialog-form" onSubmit={event=>void saveNews(event)}><DialogHeader><DialogTitle>ニュースを登録</DialogTitle><DialogDescription>月次マガジン生成時に参照するニュースを追加します。</DialogDescription></DialogHeader><label>タイトル<input required value={newsForm.title} onChange={event=>setNewsForm(current=>({...current,title:event.target.value}))}/></label><label>本文<textarea required rows={6} value={newsForm.body} onChange={event=>setNewsForm(current=>({...current,body:event.target.value}))}/></label><div><label>カテゴリ<select value={newsForm.category} onChange={event=>setNewsForm(current=>({...current,category:event.target.value as NewsCategory}))}>{Object.entries(newsCategories).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>公開日時<input required type="datetime-local" value={newsForm.published_at} onChange={event=>setNewsForm(current=>({...current,published_at:event.target.value}))}/></label></div><div><label>出典名<input value={newsForm.source_name??''} onChange={event=>setNewsForm(current=>({...current,source_name:event.target.value||null}))}/></label><label>参考URL<input type="url" value={newsForm.source_url??''} onChange={event=>setNewsForm(current=>({...current,source_url:event.target.value||null}))}/></label></div><DialogFooter><DialogClose type="button" className="secondary-button">キャンセル</DialogClose><button className="primary-button" disabled={busy}>登録する</button></DialogFooter></form></DialogContent></Dialog>
  </>
}
