import { createClient, type SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2'

export const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
export const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json'}})
export function clients(request:Request){const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,authorization=request.headers.get('Authorization');if(!authorization)throw new Error('Unauthorized');return{caller:createClient(url,anon,{global:{headers:{Authorization:authorization}}}),admin:createClient(url,service)}}
export async function authorizedUser(caller:SupabaseClient,admin:SupabaseClient,facilityId:string,write=false){const{data:{user},error}=await caller.auth.getUser();if(error||!user)throw new Error('Unauthorized');const{data:profile}=await admin.from('profiles').select('role').eq('id',user.id).single();if(profile?.role==='admin')return user;if(write&&profile?.role==='consultant')throw new Error('Consultants have read-only access');const table=profile?.role==='consultant'?'facility_consultants':'facility_users',column=profile?.role==='consultant'?'consultant_id':'user_id';const{data}=await admin.from(table).select('id').eq('facility_id',facilityId).eq(column,user.id).maybeSingle();if(!data)throw new Error('Facility access denied');return user}
export function oauthConfig(){const clientId=Deno.env.get('GOOGLE_CLIENT_ID'),clientSecret=Deno.env.get('GOOGLE_CLIENT_SECRET'),redirectUri=Deno.env.get('GOOGLE_REDIRECT_URI'),appUrl=Deno.env.get('APP_URL');if(!clientId||!clientSecret||!redirectUri||!appUrl)throw new Error('Google OAuth secrets are not configured');return{clientId,clientSecret,redirectUri,appUrl:appUrl.replace(/\/$/,'')}}
export async function exchangeCode(code:string){const config=oauthConfig();const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:config.clientId,client_secret:config.clientSecret,redirect_uri:config.redirectUri,grant_type:'authorization_code'})});if(!response.ok)throw new Error(`Token exchange failed (${response.status})`);return await response.json() as {access_token:string;refresh_token?:string}}
export type GBPLocation={accountId:string;accountName:string;locationId:string;locationName:string}
export async function listLocations(accessToken:string){const headers={Authorization:`Bearer ${accessToken}`};const accountResponse=await fetch('https://mybusinessaccountmanagement.googleapis.com/v1/accounts?pageSize=20',{headers});if(!accountResponse.ok)throw new Error(`GBP accounts returned ${accountResponse.status}`);const{accounts=[]}=await accountResponse.json() as {accounts?:Array<{name:string;accountName?:string}>};const locations:GBPLocation[]=[];for(const account of accounts){const response=await fetch(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations?readMask=name,title,metadata&pageSize=100`,{headers});if(!response.ok)continue;const body=await response.json() as {locations?:Array<{name:string;title?:string}>};for(const location of body.locations??[])locations.push({accountId:account.name.replace('accounts/',''),accountName:account.accountName??account.name,locationId:location.name.replace('locations/',''),locationName:location.title??location.name})}return locations}
