import { ArrowRight, Eye, MessageCircleReply, Sparkles, Star, Target, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useCurrentFacility } from '../features/console/use-console'
import { useLatestMEOScore } from '../features/meo-score/use-meo-score'
import { useReviewsQuery } from '../features/reviews/hooks/use-reviews'

function Stars({value}:{value:number}){return <span className="stars">{[1,2,3,4,5].map(n=><Star key={n} size={14} fill={n<=value?'currentColor':'none'}/>)}</span>}
function Metric({label,value,unit,status,tone,icon:Icon}:{label:string;value:string;unit:string;status:string;tone:string;icon:typeof Target}){return <article className="metric-card"><div className="metric-head"><span>{label}</span><span className={`metric-icon ${tone}`}><Icon size={19}/></span></div><div className="metric-value">{value}<small>{unit}</small></div><div className="metric-foot"><span className={`status ${tone}`}>{status}</span></div></article>}

export default function Index(){
  const{data:facility}=useCurrentFacility(),{data:reviews=[]}=useReviewsQuery(),{data:scores=[]}=useLatestMEOScore()
  const replied=reviews.filter(item=>item.replied).length,unreplied=reviews.length-replied,rate=reviews.length?Math.round(replied/reviews.length*100):0
  const average=reviews.length?reviews.reduce((sum,item)=>sum+item.rating,0)/reviews.length:0,latest=scores[0]
  const chart=[...scores].reverse().map(item=>({month:new Date(item.recorded_month).toLocaleDateString('ja-JP',{month:'short'}),score:item.score}))
  const change=chart.length>1?chart.at(-1)!.score-chart[0].score:0
  return <div className="dashboard">
    <header className="page-heading"><p>{new Date().toLocaleDateString('ja-JP')} ・ {facility?.name??'施設情報を読み込み中'}</p><h1>おはようございます</h1><span>今日もお客様とのつながりを育てましょう。</span></header>
    <section className="action-panel"><div className="action-summary"><span className="spark"><Sparkles size={22}/></span><div><p>今日のお店の状態</p><h2>{unreplied?'口コミへの対応があります':'おおむね良好です'}</h2></div><p className="summary-copy">{reviews.length?<>未返信の<strong>{unreplied}件</strong>を確認しましょう。</>:'口コミを同期すると対応状況が表示されます。'}</p></div><div className="today-tasks"><h3>今日やること</h3><Link to="/reviews"><span className={`task-dot ${unreplied?'urgent':''}`}/><span>口コミを確認する（未返信 {unreplied}件）</span><ArrowRight size={16}/></Link><Link to="/posts"><span className="task-dot"/><span>Google投稿を作る</span><ArrowRight size={16}/></Link></div></section>
    <section className="metric-grid"><Metric label="MEOスコア" value={latest?String(latest.score):'—'} unit=" / 100点" status={latest?'最新集計':'未集計'} tone="blue" icon={Target}/><Metric label="口コミ平均" value={reviews.length?average.toFixed(1):'—'} unit=" / 5.0" status={reviews.length?`${reviews.length}件`:'未同期'} tone="gold" icon={Star}/><Metric label="未返信口コミ" value={String(unreplied)} unit="件" status={unreplied?'要対応':'対応完了'} tone="red" icon={MessageCircleReply}/><Metric label="検索表示回数" value={String(latest?.search_views??0)} unit="回" status={latest?'最新集計':'未集計'} tone="green" icon={Eye}/></section>
    <section className="two-column"><article className="panel"><div className="panel-title"><h2>口コミへの返信状況</h2><span className="pill green">返信率 {rate}%</span></div><div className="reply-stats"><div><span>返信済み</span><div className="bar"><i style={{width:`${rate}%`}}/></div><strong>{replied}件</strong></div><div><span>未返信</span><div className="bar red"><i style={{width:`${reviews.length?100-rate:0}%`}}/></div><strong className="red-text">{unreplied}件</strong></div><footer><b>{rate}%</b><p>{reviews.length?'同期済み口コミに対する返信率です。':'口コミはまだ同期されていません。'}</p></footer></div></article><article className="panel"><div className="panel-title"><h2>MEOスコア推移 <small>直近6か月</small></h2>{chart.length>1&&<span className="change"><TrendingUp size={14}/>{change>0?'+':''}{change}点</span>}</div><div className="chart">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid stroke="#eee" vertical={false}/><XAxis dataKey="month"/><YAxis domain={[0,100]}/><Tooltip/><Area type="monotone" dataKey="score" stroke="#2383E2" fill="#EBF3FB"/></AreaChart></ResponsiveContainer>:<p className="loading-row">まだ集計データがありません。</p>}</div></article></section>
    <section className="panel reviews"><div className="panel-title"><h2>最近の口コミ</h2><Link to="/reviews">すべて見る <ArrowRight size={15}/></Link></div>{reviews.slice(0,3).map(item=><article className={!item.replied?'unreplied':''} key={item.id}><span className="review-avatar">{item.author.slice(0,1)}</span><div className="review-body"><div className="review-meta"><Stars value={item.rating}/><strong>{item.author}</strong><small>{item.date}</small><span className={`pill ${item.replied?'':'red'}`}>{item.replied?'返信済み':'未返信'}</span></div><p>{item.text}</p></div><Link className={item.replied?'secondary-button':'primary-button'} to={`/reviews/${item.id}`}>{item.replied?'返信を見る':'AIで返信'}</Link></article>)}{!reviews.length&&<p className="loading-row">口コミデータはまだありません。</p>}</section>
  </div>
}
