import { Search, Sparkles, Star } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useReviewsQuery } from '../features/reviews/hooks/use-reviews'

export default function Reviews() {
  const { data: reviews = [] } = useReviewsQuery(), [status, setStatus] = useState<'all'|'unreplied'|'replied'>('all'), [rating, setRating] = useState(0), [query, setQuery] = useState('')
  const filtered = useMemo(() => reviews.filter(r => (!rating || r.rating === rating) && (status === 'all' || (status === 'replied') === r.replied) && `${r.author}${r.title}${r.text}`.toLowerCase().includes(query.toLowerCase())), [reviews,status,rating,query])
  return <section className="page-stack"><header className="section-heading"><div><h1>口コミ管理</h1><p>お客様の声を確認し、まだ返信していない口コミに対応できます。</p></div><span className="count-badge">未返信 {reviews.filter(r=>!r.replied).length}件</span></header><div className="filters"><div className="segments">{(['all','unreplied','replied'] as const).map(v=><button className={status===v?'active':''} onClick={()=>setStatus(v)} key={v}>{v==='all'?'すべて':v==='unreplied'?'未返信':'返信済み'}</button>)}</div><div className="rating-filters">{[5,4,3,2,1].map(n=><button key={n} onClick={()=>setRating(rating===n?0:n)} className={rating===n?'active':''}><Star size={13} fill="currentColor" />{n}</button>)}</div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="口コミを検索" /></label></div><div className="table-card"><div className="review-table head"><span>評価</span><span>投稿者</span><span>投稿日</span><span>口コミ内容</span><span>状態</span><span /></div>{filtered.map(r=><div className={`review-table ${!r.replied?'highlight':''}`} key={r.id}><span className="stars table-stars">{Array.from({length:5},(_,i)=><Star key={i} size={13} fill={i<r.rating?'currentColor':'none'}/>)}</span><strong>{r.author}</strong><small>{r.date}</small><div className="review-cell"><b>{r.title}</b><p>{r.text}</p></div><span><i className={`pill ${r.replied?'green':'red'}`}>{r.replied?'返信済み':'未返信'}</i></span><Link className={r.replied?'secondary-button':'primary-button'} to={`/reviews/${r.id}`}>{!r.replied&&<Sparkles size={14}/>} {r.replied?'返信を見る':'AIで返信'}</Link></div>)}{!filtered.length&&<div className="empty-inline">条件に一致する口コミはありません。</div>}</div></section>
}
