import { Check, Download, Link2, LogOut, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { useCurrentFacility, useUpdateCurrentFacility } from '../features/console/use-console'
import { useFacilitySettings, useSaveFacilitySettings, type FacilitySettings } from '../features/settings/use-facility-settings'
import { useGBPOAuth, type GBPLocation } from '../features/settings/use-gbp-oauth'
import type { Facility } from '../types/database.types'

function Toggle({on,set}:{on:boolean;set:(value:boolean)=>void}){return <button className={`toggle ${on?'on':''}`} onClick={()=>set(!on)} aria-pressed={on}><span/></button>}
export default function Settings(){const facility=useCurrentFacility(),preferences=useFacilitySettings();if(facility.isLoading||preferences.isLoading)return <section className="page-stack"><p>設定を読み込んでいます…</p></section>;return <SettingsForm key={facility.data?.id} facility={facility.data} initial={preferences.data??{auto_draft_reply:true,auto_post_high_rating:false,email_notifications:true}}/>}

function SettingsForm({facility,initial}:{facility:Facility|undefined;initial:FacilitySettings}){
  const gbp=useGBPOAuth(),updateFacility=useUpdateCurrentFacility(),savePreferences=useSaveFacilitySettings(),connection=gbp.status.data
  const[name,setName]=useState(facility?.name??''),[phone,setPhone]=useState(facility?.phone??''),[address,setAddress]=useState(facility?.address??''),[preferences,setPreferences]=useState(initial),[selected,setSelected]=useState(''),[saved,setSaved]=useState(false)
  const locations=connection?.locations??[],selectedLocation=locations.find(item=>`${item.accountId}:${item.locationId}`===selected)
  const save=async()=>{setSaved(false);await Promise.all([updateFacility.mutateAsync({name,phone,address}),savePreferences.mutateAsync(preferences)]);setSaved(true)}
  const busy=updateFacility.isPending||savePreferences.isPending
  return <section className="page-stack"><header className="section-heading"><div><h1>設定</h1><p>施設情報、Google連携、AI返信と通知の設定を管理します。</p></div></header>
    <div className="settings-card"><h2>施設情報</h2><div className="field-grid"><label>施設名<input value={name} onChange={e=>setName(e.target.value)}/></label><label>電話番号<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="wide">住所<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div></div>
    <div className="settings-card"><h2>Googleビジネスプロフィール</h2>{gbp.result==='connected'&&<p className="auth-message gbp-message">Googleビジネスプロフィールを接続しました。</p>}{gbp.result==='error'&&<p className="auth-error gbp-message">接続に失敗しました：{gbp.message}</p>}<div className={`connection ${connection?.connected?'connected':''}`}><Link2 size={20}/><div><strong>{connection?.connected?'Googleと連携済み':'Google連携は未設定です'}</strong><small>{connection?.connected?`${connection.locationName??'施設名未取得'}・更新 ${connection.lastSyncedAt?new Date(connection.lastSyncedAt).toLocaleString('ja-JP'):'—'}`:'Googleアカウントで認証し、管理する施設を選択します'}</small></div>{connection?.connected?<><button disabled={gbp.syncReviews.isPending} onClick={()=>gbp.syncReviews.mutate()}><Download size={15}/>{gbp.syncReviews.isPending?'同期中…':'口コミを同期'}</button><button disabled={gbp.disconnect.isPending} onClick={()=>{if(window.confirm('Google連携を解除しますか？'))gbp.disconnect.mutate()}}><LogOut size={15}/>連携解除</button></>:<button disabled={gbp.connect.isPending} onClick={()=>gbp.connect.mutate()}><Link2 size={15}/>{gbp.connect.isPending?'接続準備中…':'Googleと接続'}</button>}<button disabled={gbp.status.isFetching} onClick={()=>void gbp.status.refetch()}><RefreshCw size={15}/>状態を確認</button></div>{gbp.syncReviews.isSuccess&&<p className="auth-message gbp-message">口コミを{gbp.syncReviews.data.synced}件同期しました。</p>}{locations.length>0&&<LocationSelector locations={locations} selected={selected} setSelected={setSelected} busy={gbp.finalize.isPending} submit={()=>selectedLocation&&gbp.finalize.mutate(selectedLocation)}/>} {(gbp.connect.error||gbp.status.error||gbp.finalize.error||gbp.disconnect.error||gbp.syncReviews.error)&&<p className="data-error gbp-message">Google連携処理に失敗しました。Functionのログを確認してください。</p>}</div>
    <div className="settings-card"><h2>AI返信</h2><div className="setting-row"><div><strong>新しい口コミの下書きを用意する</strong><small>口コミが届いた時点でAI返信案を作成します。</small></div><Toggle on={preferences.auto_draft_reply} set={value=>setPreferences(current=>({...current,auto_draft_reply:value}))}/></div><div className="setting-row"><div><strong>高評価の口コミへ自動返信する</strong><small>確認なしで返信する設定です。</small></div><Toggle on={preferences.auto_post_high_rating} set={value=>setPreferences(current=>({...current,auto_post_high_rating:value}))}/></div></div>
    <div className="settings-card"><h2>通知</h2><div className="setting-row"><div><strong>新しい口コミをメールで知らせる</strong><small>未返信を見逃さないための通知設定です。</small></div><Toggle on={preferences.email_notifications} set={value=>setPreferences(current=>({...current,email_notifications:value}))}/></div></div>
    {(updateFacility.error||savePreferences.error)&&<p className="data-error">設定を保存できませんでした。</p>}<button className="save-settings" disabled={busy} onClick={()=>void save()}><Check size={16}/>{busy?'保存中…':saved?'保存しました':'設定を保存する'}</button>
  </section>
}
function LocationSelector({locations,selected,setSelected,busy,submit}:{locations:GBPLocation[];selected:string;setSelected:(value:string)=>void;busy:boolean;submit:()=>void}){return <div className="gbp-location-selector"><strong>接続する施設を選択</strong><p>Googleアカウントで管理している施設が複数見つかりました。</p><select value={selected} onChange={event=>setSelected(event.target.value)}><option value="">施設を選択してください</option>{locations.map(location=><option key={`${location.accountId}:${location.locationId}`} value={`${location.accountId}:${location.locationId}`}>{location.locationName}（{location.accountName}）</option>)}</select><button className="primary-button" disabled={!selected||busy} onClick={submit}>{busy?'接続中…':'この施設を接続する'}</button></div>}
