import { ArrowLeft, Plus, Trash2, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { useAddFacilityUser, useFacility, useFacilityUsers, useManageFacilityUser } from '../../features/console/use-console'

export default function ConsoleFacilityUsers(){
  const{facilityId}=useParams(),isAdmin=useLocation().pathname.startsWith('/admin'),base=isAdmin?`/admin/facilities/${facilityId}`:`/console/${facilityId}`
  const{data:facility}=useFacility(facilityId),{data:users=[],isLoading,error}=useFacilityUsers(facilityId),add=useAddFacilityUser(facilityId),manage=useManageFacilityUser(facilityId)
  const[open,setOpen]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('')
  const[pendingDelete,setPendingDelete]=useState<(typeof users)[number]|null>(null)
  const submit=async(event:React.FormEvent)=>{event.preventDefault();await add.mutateAsync({name:name.trim(),email:email.trim(),password});setName('');setEmail('');setPassword('');setOpen(false)}
  return <section className="role-page"><Link className="back" to={base}><ArrowLeft size={15}/>施設詳細へ戻る</Link><header className="role-heading"><div><span>{isAdmin?'ADMIN':'CONSULTANT'}・施設ユーザー</span><h1>{facility?.name??'施設'}のユーザー</h1><p>この施設へログインできる担当者を管理します。</p></div><button onClick={()=>setOpen(current=>!current)}><Plus size={15}/>{open?'閉じる':'ユーザーを追加'}</button></header>
    {open&&<form className="inline-form" onSubmit={event=>void submit(event)}><label>氏名<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>メールアドレス<input required type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>初期パスワード<input required type="password" minLength={8} value={password} onChange={event=>setPassword(event.target.value)}/></label>{add.error&&<p className="data-error">{add.error.message}</p>}<button disabled={add.isPending}>{add.isPending?'追加中…':'施設ユーザーを追加'}</button></form>}
    {add.isSuccess&&<p className="data-success">施設ユーザーを追加しました。</p>}{error&&<p className="data-error">施設ユーザーを取得できませんでした。</p>}
    {manage.error&&<p className="data-error">{manage.error.message}</p>}
    <div className="data-table"><div className="data-row facility-user-row head"><span>氏名</span><span>メール</span><span>施設内権限</span><span>操作</span></div>{isLoading?<p className="loading-row">読み込み中…</p>:users.map(user=><div className="data-row facility-user-row" key={user.userId}><strong><UserRound size={15}/>{user.name||'名称未設定'}</strong><span>{user.email||'メール未設定'}</span><select aria-label={`${user.name||user.email||'施設ユーザー'}の施設内権限`} value={user.roleInFacility} disabled={manage.isPending} onChange={event=>manage.mutate({userId:user.userId,action:'update_role',roleInFacility:event.target.value as'owner'|'staff'})}><option value="owner">オーナー</option><option value="staff">スタッフ</option></select><button className="danger-action" disabled={manage.isPending} onClick={()=>setPendingDelete(user)}><Trash2 size={14}/>削除</button></div>)}{!isLoading&&!users.length&&<p className="loading-row">施設ユーザーはまだ登録されていません。</p>}</div>
    {pendingDelete&&<div className="role-dialog-backdrop" role="presentation" onMouseDown={()=>!manage.isPending&&setPendingDelete(null)}><div className="role-dialog" role="dialog" aria-modal="true" aria-labelledby="facility-user-delete-title" onMouseDown={event=>event.stopPropagation()}><span>ユーザー削除の確認</span><h2 id="facility-user-delete-title">{pendingDelete.name||pendingDelete.email||'施設ユーザー'}</h2><p>この施設へのアクセス権を削除します。他の施設にも所属していない場合は、ログインアカウントも削除されます。</p><footer><button className="secondary-button" disabled={manage.isPending} onClick={()=>setPendingDelete(null)}>キャンセル</button><button className="danger-action" disabled={manage.isPending} onClick={()=>manage.mutate({userId:pendingDelete.userId,action:'remove'},{onSuccess:()=>setPendingDelete(null)})}>{manage.isPending?'削除中…':'削除する'}</button></footer></div></div>}
  </section>
}
