import { BarChart3, BriefcaseBusiness, ClipboardList, ExternalLink, Pencil, Save, MessageSquareText, Users } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { useFacility, useFacilityGBPStatus, useUpdateFacility } from '../../features/console/use-console'
import type { Facility } from '../../types/database.types'

const categoryLabels={ryokan:'旅館',hotel:'ホテル',guesthouse:'ゲストハウス',other:'その他'} as const
export default function ConsoleFacilityDetail(){
  const{facilityId}=useParams(),isAdmin=useLocation().pathname.startsWith('/admin'),base=isAdmin?`/admin/facilities/${facilityId}`:`/console/${facilityId}`
  const{data,isLoading,error}=useFacility(facilityId),{data:gbp}=useFacilityGBPStatus(facilityId),update=useUpdateFacility(facilityId)
  const[editing,setEditing]=useState(false),[form,setForm]=useState({name:'',prefecture:'',category:'other' as NonNullable<Facility['category']>,address:'',phone:''})
  const category=data?.category?categoryLabels[data.category]:'—'
  const toggleEditing=()=>{if(editing){setEditing(false);return}if(data)setForm({name:data.name,prefecture:data.prefecture??'',category:data.category??'other',address:data.address??'',phone:data.phone??''});setEditing(true)}
  const save=async(event:React.FormEvent)=>{event.preventDefault();await update.mutateAsync({...form,name:form.name.trim(),prefecture:form.prefecture.trim(),address:form.address.trim(),phone:form.phone.trim()});setEditing(false)}
  return <section className="role-page"><header className="role-heading"><div><span>{isAdmin?'ADMIN':'CONSULTANT'}・施設管理</span><h1>{isLoading?'読み込み中…':data?.name??'施設詳細'}</h1><p>{data?.prefecture}・{category}</p></div>{isAdmin&&data&&<button onClick={toggleEditing}><Pencil size={15}/>{editing?'編集を閉じる':'基本情報を編集'}</button>}</header>{error&&<p className="data-error">施設情報を取得できません。</p>}
    {editing&&<form className="facility-form facility-edit-form" onSubmit={event=>void save(event)}><fieldset><legend>施設基本情報</legend><div><label>施設名<input required value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value}))}/></label><label>都道府県<input required value={form.prefecture} onChange={event=>setForm(current=>({...current,prefecture:event.target.value}))}/></label></div><div><label>カテゴリ<select value={form.category} onChange={event=>setForm(current=>({...current,category:event.target.value as NonNullable<Facility['category']>}))}><option value="ryokan">旅館</option><option value="hotel">ホテル</option><option value="guesthouse">ゲストハウス</option><option value="other">その他</option></select></label><label>電話番号<input value={form.phone} onChange={event=>setForm(current=>({...current,phone:event.target.value}))}/></label></div><label>住所<input value={form.address} onChange={event=>setForm(current=>({...current,address:event.target.value}))}/></label></fieldset>{update.error&&<p className="data-error">施設情報を更新できませんでした。</p>}<button disabled={update.isPending}><Save size={15}/>{update.isPending?'保存中…':'変更を保存する'}</button></form>}
    {update.isSuccess&&!editing&&<p className="data-success">施設基本情報を更新しました。</p>}
    <div className="facility-action-grid"><Link to={`${base}/workspace`}><BarChart3 size={20}/><div><strong>施設ページを見る</strong><small>実データのダッシュボードを表示</small></div><ExternalLink size={15}/></Link><Link to={`${base}/reviews`}><MessageSquareText size={20}/><div><strong>口コミ状況</strong><small>口コミと返信状況を確認</small></div><ExternalLink size={15}/></Link><Link to={`${base}/onboarding`}><ClipboardList size={20}/><div><strong>ヒアリング編集</strong><small>施設情報と運用目標を編集</small></div><ExternalLink size={15}/></Link><Link to={`${base}/users`}><Users size={20}/><div><strong>施設ユーザー</strong><small>所属ユーザーの確認と追加</small></div><ExternalLink size={15}/></Link>{isAdmin&&<Link to={`${base}/consultants`}><BriefcaseBusiness size={20}/><div><strong>担当コンサルタント</strong><small>担当者の割り当てと解除</small></div><ExternalLink size={15}/></Link>}</div><div className="stat-grid"><article className="stat-card"><span>GBP連携</span><strong className="small-value">{gbp?.connected?'連携済み':'未連携'}</strong>{gbp?.locationName&&<small>{gbp.locationName}</small>}</article><article className="stat-card"><span>施設ID</span><strong className="small-value">{facilityId}</strong></article></div></section>
}
