import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog'
import { type GBPTip, type TipCategory, type TipImportance, type TipInput, useTipMutations, useTips } from '../hooks/use-tips'

const categoryLabels:Record<TipCategory,string>={post:'投稿',review:'口コミ',photo:'写真',info:'情報',general:'一般'}
const importanceLabels:Record<TipImportance,string>={high:'重要',medium:'参考',low:'低'}
const empty:TipInput={category:'post',title:'',body:'',importance:'medium',source_url:null,is_published:true}

export function TipsAdminPanel(){
  const{data=[],isLoading,error}=useTips(),mutations=useTipMutations(),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState<TipInput>(empty)
  const busy=mutations.create.isPending||mutations.update.isPending||mutations.remove.isPending||mutations.togglePublished.isPending
  const beginCreate=()=>{setEditingId(null);setForm(empty);setOpen(true)}
  const beginEdit=(tip:GBPTip)=>{setEditingId(tip.id);setForm({category:tip.category,title:tip.title,body:tip.body,importance:tip.importance,source_url:tip.source_url,is_published:tip.is_published});setOpen(true)}
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(editingId)await mutations.update.mutateAsync({id:editingId,...form});else await mutations.create.mutateAsync(form);setOpen(false)}
  const remove=(tip:GBPTip)=>{if(window.confirm(`チップス「${tip.title}」を削除しますか？`))mutations.remove.mutate(tip.id)}
  const mutationError=mutations.create.error||mutations.update.error||mutations.remove.error||mutations.togglePublished.error
  return <><header className="role-heading"><div><span>ADMIN</span><h1>チップス管理</h1><p>ユーザーとコンサルタントに表示するGBP運用情報を管理します。</p></div><button onClick={beginCreate}><Plus size={15}/>チップスを追加</button></header>{(error||mutationError)&&<p className="data-error">チップスの操作に失敗しました。</p>}<div className="data-table"><div className="data-row tips-admin-row head"><span>タイトル</span><span>カテゴリ</span><span>重要度</span><span>公開状態</span><span>操作</span></div>{isLoading?<p className="loading-row">読み込み中…</p>:data.map(tip=><div className="data-row tips-admin-row" key={tip.id}><strong>{tip.title}</strong><span>{categoryLabels[tip.category]}</span><span className={`tip-importance ${tip.importance}`}>{importanceLabels[tip.importance]}</span><button className={`publish-toggle ${tip.is_published?'on':''}`} disabled={busy} onClick={()=>mutations.togglePublished.mutate({id:tip.id,isPublished:!tip.is_published})}>{tip.is_published?'公開':'非公開'}</button><div className="tips-admin-actions"><button aria-label={`${tip.title}を編集`} disabled={busy} onClick={()=>beginEdit(tip)}><Pencil size={14}/></button><button className="danger-action" aria-label={`${tip.title}を削除`} disabled={busy} onClick={()=>remove(tip)}><Trash2 size={14}/></button></div></div>)}{!isLoading&&!data.length&&<p className="loading-row">チップスはまだありません。</p>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><form className="tip-dialog-form" onSubmit={event=>void save(event)}><DialogHeader><DialogTitle>{editingId?'チップスを編集':'チップスを追加'}</DialogTitle><DialogDescription>GBP運用に役立つ情報を登録します。</DialogDescription></DialogHeader><label>タイトル<input required value={form.title} onChange={event=>setForm(current=>({...current,title:event.target.value}))}/></label><label>本文<textarea required rows={5} value={form.body} onChange={event=>setForm(current=>({...current,body:event.target.value}))}/></label><div><label>カテゴリ<select value={form.category} onChange={event=>setForm(current=>({...current,category:event.target.value as TipCategory}))}>{Object.entries(categoryLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>重要度<select value={form.importance} onChange={event=>setForm(current=>({...current,importance:event.target.value as TipImportance}))}>{Object.entries(importanceLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><label>参考リンク（任意）<input type="url" value={form.source_url??''} onChange={event=>setForm(current=>({...current,source_url:event.target.value||null}))}/></label><label className="checkbox-label"><input type="checkbox" checked={form.is_published} onChange={event=>setForm(current=>({...current,is_published:event.target.checked}))}/>公開する</label><DialogFooter><DialogClose type="button" className="secondary-button">キャンセル</DialogClose><button className="primary-button" disabled={busy}>{busy?'保存中…':'保存する'}</button></DialogFooter></form></DialogContent></Dialog>
  </>
}
