import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../auth/use-auth'
import type { Facility, FacilityOnboarding } from '../../types/database.types'
const client=()=>{if(!supabase)throw new Error('Supabaseが設定されていません');return supabase}
export function useAssignedFacilities(){const {user}=useAuth();return useQuery({queryKey:['console','facilities',user?.id],enabled:Boolean(user),queryFn:async()=>{const {data:memberships,error:membershipError}=await client().from('facility_consultants').select('facility_id').eq('consultant_id',user!.id);if(membershipError)throw membershipError;const ids=(memberships??[]).map(item=>item.facility_id);if(!ids.length)return[];const {data,error}=await client().from('facilities').select('id,name,prefecture,category,gbp_place_id,created_at').in('id',ids);if(error)throw error;return data as Facility[]}})}
export function useFacility(facilityId?:string){return useQuery({queryKey:['facility',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const {data,error}=await client().from('facilities').select('id,name,prefecture,category,address,phone,gbp_place_id,created_at').eq('id',facilityId!).single();if(error)throw error;return data as Facility}})}
export function useUpdateFacility(facilityId?:string){const qc=useQueryClient();return useMutation({mutationFn:async(values:Pick<Facility,'name'|'prefecture'|'category'|'address'|'phone'>)=>{if(!facilityId)throw new Error('施設が選択されていません');const{error}=await client().from('facilities').update(values).eq('id',facilityId);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:['facility',facilityId]});qc.invalidateQueries({queryKey:['admin','facilities']});qc.invalidateQueries({queryKey:['console','facilities']})}})}
export function useCurrentFacility(){const{user}=useAuth();return useFacility(user?.currentFacilityId)}
export function useUpdateCurrentFacility(){const{user}=useAuth(),qc=useQueryClient();return useMutation({mutationFn:async(values:Pick<Facility,'name'|'address'|'phone'>)=>{if(!user?.currentFacilityId)throw new Error('施設が選択されていません');const{error}=await client().from('facilities').update(values).eq('id',user.currentFacilityId);if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:['facility',user?.currentFacilityId]})})}
export function useOnboarding(facilityId?:string){return useQuery({queryKey:['onboarding',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const {data,error}=await client().from('facility_onboarding').select('*').eq('facility_id',facilityId!).maybeSingle();if(error)throw error;return data as FacilityOnboarding|null}})}
export function useFacilityWorkspace(facilityId?:string){return useQuery({queryKey:['facility-workspace',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const db=client();const[reviews,scores,posts]=await Promise.all([db.from('reviews').select('id,author_name,rating,text,replied,reply_text,posted_at').eq('facility_id',facilityId!).order('posted_at',{ascending:false}),db.from('meo_scores').select('score,reply_rate,avg_rating,search_views,recorded_month').eq('facility_id',facilityId!).order('recorded_month',{ascending:false}).limit(6),db.from('gbp_posts').select('id,status,created_at').eq('facility_id',facilityId!)]);if(reviews.error)throw reviews.error;if(scores.error)throw scores.error;if(posts.error)throw posts.error;return{reviews:reviews.data??[],scores:scores.data??[],posts:posts.data??[]}}})}
export function useFacilityUsers(facilityId?:string){return useQuery({queryKey:['facility-users',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const db=client(),{data:memberships,error}=await db.from('facility_users').select('user_id,role_in_facility,created_at').eq('facility_id',facilityId!);if(error)throw error;const ids=(memberships??[]).map(item=>item.user_id);if(!ids.length)return[];const{data:profiles,error:profileError}=await db.from('profiles').select('id,name,email').in('id',ids);if(profileError)throw profileError;return memberships!.map(item=>({userId:item.user_id,name:profiles?.find(profile=>profile.id===item.user_id)?.name??null,email:profiles?.find(profile=>profile.id===item.user_id)?.email??null,roleInFacility:item.role_in_facility as 'owner'|'staff',createdAt:item.created_at}))}})}
export function useAddFacilityUser(facilityId?:string){const qc=useQueryClient();return useMutation({mutationFn:async(input:{name:string;email:string;password:string})=>{if(!facilityId)throw new Error('施設が選択されていません');const{data,error}=await client().functions.invoke('add-user-to-facility',{body:{facility_id:facilityId,...input}});if(error)throw new Error((data as {error?:string})?.error??error.message);return data as{user_id:string}},onSuccess:()=>qc.invalidateQueries({queryKey:['facility-users',facilityId]})})}
export function useManageFacilityUser(facilityId?:string){const qc=useQueryClient();return useMutation({mutationFn:async(input:{userId:string;action:'update_role'|'remove';roleInFacility?:'owner'|'staff'})=>{if(!facilityId)throw new Error('施設が選択されていません');const{data,error}=await client().functions.invoke('manage-facility-user',{body:{facility_id:facilityId,user_id:input.userId,action:input.action,role_in_facility:input.roleInFacility}});if(error)throw new Error((data as{error?:string})?.error??error.message);return data},onSuccess:()=>qc.invalidateQueries({queryKey:['facility-users',facilityId]})})}
export function useFacilityGBPStatus(facilityId?:string){return useQuery({queryKey:['facility-gbp-status',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const{data,error}=await client().functions.invoke('gbp-oauth-status',{body:{facility_id:facilityId}});if(error)throw error;return data as{connected:boolean;locationName?:string;lastSyncedAt?:string}}})}
export function useCreateFacility(){const qc=useQueryClient();return useMutation({mutationFn:async(input:{facility:{name:string;prefecture:string;category:string};user:{name:string;email:string;password:string};draft_note:string})=>{const {data,error}=await client().functions.invoke('invite-user',{body:input});if(error)throw error;return data as {facility_id:string;user_id:string}},onSuccess:()=>qc.invalidateQueries({queryKey:['console']})})}
export function useSaveOnboarding(facilityId:string){const qc=useQueryClient();return useMutation({mutationFn:async(values:Partial<FacilityOnboarding>)=>{const {error}=await client().from('facility_onboarding').upsert({facility_id:facilityId,...values},{onConflict:'facility_id'});if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:['onboarding',facilityId]})})}
