import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../auth/use-auth'
import type { Facility, FacilityOnboarding } from '../../types/database.types'
const client=()=>{if(!supabase)throw new Error('Supabaseが設定されていません');return supabase}
export function useAssignedFacilities(){const {user}=useAuth();return useQuery({queryKey:['console','facilities',user?.id],enabled:Boolean(user),queryFn:async()=>{const {data:memberships,error:membershipError}=await client().from('facility_consultants').select('facility_id').eq('consultant_id',user!.id);if(membershipError)throw membershipError;const ids=(memberships??[]).map(item=>item.facility_id);if(!ids.length)return[];const {data,error}=await client().from('facilities').select('id,name,prefecture,category,gbp_place_id,created_at').in('id',ids);if(error)throw error;return data as Facility[]}})}
export function useFacility(facilityId?:string){return useQuery({queryKey:['facility',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const {data,error}=await client().from('facilities').select('id,name,prefecture,category,gbp_place_id,created_at').eq('id',facilityId!).single();if(error)throw error;return data as Facility}})}
export function useOnboarding(facilityId?:string){return useQuery({queryKey:['onboarding',facilityId],enabled:Boolean(facilityId),queryFn:async()=>{const {data,error}=await client().from('facility_onboarding').select('*').eq('facility_id',facilityId!).maybeSingle();if(error)throw error;return data as FacilityOnboarding|null}})}
export function useCreateFacility(){const qc=useQueryClient();return useMutation({mutationFn:async(input:{facility:{name:string;prefecture:string;category:string};user:{name:string;email:string;password:string};draft_note:string})=>{const {data,error}=await client().functions.invoke('invite-user',{body:input});if(error)throw error;return data as {facility_id:string;user_id:string}},onSuccess:()=>qc.invalidateQueries({queryKey:['console']})})}
export function useSaveOnboarding(facilityId:string){const qc=useQueryClient();return useMutation({mutationFn:async(values:Partial<FacilityOnboarding>)=>{const {error}=await client().from('facility_onboarding').upsert({facility_id:facilityId,...values},{onConflict:'facility_id'});if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:['onboarding',facilityId]})})}
